# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "typescript"
      - dependency-name: "@types/node"
        versions: [">= 23"]
      - dependency-name: "eslint-plugin-cypress"
        versions: [">= 4"]
      # Pinned to 4.4.0 due to breaking changes in 4.4.1 (https://github.com/vuejs/router/discussions/2321)
      - dependency-name: "vue-router"
        versions: ["<= 4.4.5"]
      # ignore @vue/eslint-config-typescript since it's only supports flat config
      - dependency-name: "@vue/eslint-config-typescript"
        versions: [">= 14"]
    groups:
      storybook:
        applies-to: version-updates
        patterns:
          - "@storybook*"
          - "storybook"
      vitest:
        applies-to: version-updates
        patterns:
          - "vitest"
          - "@vitest*"
