shared:
  ci_success: &ci_success
    - "check-success=CI / Build and Test"
  queue_merge_conditions: &queue_merge_conditions
    - -label=Hold merge
    - -label=Addressing issues
    - -draft
    - or :
      - "#approved-reviews-by>=1"
      - label=Ready to merge


queue_rules:
  - name: default
    batch_size: 3
    conditions:
      - and: *queue_merge_conditions

pull_request_rules:
  - name: Add PR to default merge queue
    conditions: *queue_merge_conditions
    actions:
      queue:
        name: default
        allow_merging_configuration_change: true
  - name: Automatically approve Dependabot PRs
    conditions:
      - author=dependabot[bot]
      - and: *ci_success
      - dependabot-update-type=version-update:semver-patch
    actions:
      review:
        type: APPROVE
  - name: Test for conflicts
    conditions:
      - conflict
    actions:
      label:
        toggle:
          - conflict
  - name: Add PR stack label for stacked PRs created by mergify
    conditions:
      - head~=mergify_cli/
    actions:
      label:
        add:
          - PR stack
