queue_rules:
  - name: default
    conditions: &default_queue_conditions
      - -label=Hold merge
      - -label=Addressing issues
      - label=Ready to merge

pull_request_rules:
  - name: Automatic merge on approval
    conditions: *default_queue_conditions
    actions:
      queue:
        name: default
        allow_merging_configuration_change: true
  - name: add label on conflicts
    conditions:
      - conflict
    actions:
      label:
        toggle:
          - conflict
  - name: Add PR stack label for stacked PRs created by mergify
    conditions:
      - head~=mergify_cli/
    actions:
      label:
        add:
          - PR stack
