queue_rules:
  - name: default
    conditions: &default_queue_conditions
      - -label=blocked
      - -label=addressing issues
      - label=review requested

pull_request_rules:
  - name: Automatic merge on approval
    conditions: *default_queue_conditions
    actions:
      queue:
        name: default
        allow_merging_configuration_change: true
  - name: add review when out of draft
    conditions:
      - -label=review requested
      - -draft
    actions:
      label:
        add:
          - review requested
  - name: add label on conflicts
    conditions:
      - conflict
    actions:
      label:
        toggle:
          - conflict
