partition_rules:
  - name: default
    fallback_partition: true

  - name: inkbeard site
    conditions:
      - files~=^apps/inkbeard/

  - name: example library
    conditions:
      - files~=^apps/ui-library/

  - name: budget it
    conditions:
      - files~=^packages/budget-it/

  - name: general ui
    conditions:
      - files~=^packages/ui-theme/
      - files~=^packages/ui-vue/
      - files~=^packages/ui/
      - files~=^packages/eslint-config/
      - files~=^packages/stylelint-config/
      - files~=^packages/typescript-config/

shared:
  ci_success: &ci_success
    - "check-success=Build and Test"
  queue_conditions: &queue_conditions
    - -label=Hold merge
    - -label=Addressing issues
    - -conflict
    - "#approved-reviews-by>=1"
  default_queue_conditions: &default_queue_conditions
      - and: *ci_success
      - and: *queue_conditions
      - author!=dependabot[bot]
  dependabot_queue_conditions: &dependabot_queue_conditions
      - and: *ci_success
      - and: *queue_conditions
      - author=dependabot[bot]
  release_queue_conditions: &release_queue_conditions
      - head=changeset-release/main
      - "#approved-reviews-by>=1"

queue_rules:
  - name: release
    queue_conditions:
      - and: *release_queue_conditions
  - name: default
    batch_size: 3
    speculative_checks: 3
    queue_conditions:
      - and: *default_queue_conditions
  - name: dependabot
    batch_size: 10
    batch_max_wait_time: 30 min
    queue_conditions:
      - and: *dependabot_queue_conditions

pull_request_rules:
  # PR approval rules
  - name: Automatically approve Dependabot PRs
    conditions:
      - author=dependabot[bot]
      - and: *ci_success
      - or:
        - dependabot-update-type=version-update:semver-minor
        - dependabot-update-type=version-update:semver-patch
    actions:
      review:
        type: APPROVE
  - name: Add bot approval for PRs ready to merge
    conditions:
      - label=Ready to merge
    actions:
      review:
        type: APPROVE
  # PR queue rules
  - name: Add PR to default queue
    conditions:
      - and: *default_queue_conditions
    actions:
      queue:
        name: default
        allow_merging_configuration_change: true
  - name: Add PR to dependabot queue
    conditions:
      - and: *dependabot_queue_conditions
    actions:
      queue:
        name: dependabot
        allow_merging_configuration_change: true
  - name: Add PR to release queue
    conditions:
      - and: *release_queue_conditions
    actions:
      queue:
        name: release
        allow_merging_configuration_change: true
  # PR test rules
  - name: Test for conflicts
    conditions:
      - conflict
    actions:
      label:
        toggle:
          - conflict
  # PR label rules
  - name: Add appropriate project labels
    conditions:
      - partition-name!=default
    actions:
      github_actions:
        workflow:
          dispatch:
            - workflow: label-maker.yaml
              inputs:
                project_name: test
  - name: Add default project label
    conditions:
      - partition-name=default
    actions:
      github_actions:
        workflow:
          dispatch:
            - workflow: label-maker.yaml
              inputs:
                project_name: default
  - name: Add PR stack label for stacked PRs created by mergify
    conditions:
      - head~=mergify_cli/
    actions:
      label:
        add:
          - PR stack
