shared:
  ci_success: &ci_success
    - "check-success=Build and Test"
  queue_conditions: &queue_conditions
    - -label=Hold merge
    - -label=Addressing issues
    - -conflict
    - "#approved-reviews-by>=1"

queue_rules:
  - name: release
    merge_conditions:
      - head=changeset-release/main
      - "#approved-reviews-by>=1"
  - name: default
    batch_size: 3
    speculative_checks: 3
    queue_conditions:
      - and: *ci_success
      - and: *queue_conditions
      - author!=dependabot[bot]
  - name: dep-update
    batch_size: 10
    batch_max_wait_time: 30 min
    queue_conditions:
      - and: *ci_success
      - and: *queue_conditions
      - author=dependabot[bot]

pull_request_rules:
  - name: Automatically approve Dependabot PRs
    conditions:
      - author=dependabot[bot]
      - and: *ci_success
      - or:
        - dependabot-update-type=version-update:semver-minor
        - dependabot-update-type=version-update:semver-patch
    actions:
      review:
        type: APPROVE
  - name: Add bot approval for PRs ready to merge
    conditions:
      - label=Ready to merge
    actions:
      review:
        type: APPROVE
  - name: Test for conflicts
    conditions:
      - conflict
    actions:
      label:
        toggle:
          - conflict
  - name: Add PR stack label for stacked PRs created by mergify
    conditions:
      - head~=mergify_cli/
    actions:
      label:
        add:
          - PR stack
