queue_rules:
  - name: default
    conditions: &default_queue_conditions
      - -label=Hold merge
      - -label=Addressing issues
      - label=Ready to merge

pull_request_rules:
  - name: Automatically approve Dependabot PRs
    conditions:
      - author=dependabot[bot]
      - or:
        - dependabot-update-type=version-update:semver-minor
        - dependabot-update-type=version-update:semver-patch
    actions:
      review:
        type: APPROVE
      label:
        add:
          - Ready to merge
  - name: add label on conflicts
    conditions:
      - conflict
    actions:
      label:
        toggle:
          - conflict
  - name: Add PR stack label for stacked PRs created by mergify
    conditions:
      - head~=mergify_cli/
    actions:
      label:
        add:
          - PR stack
