name: 'Prepare job'
description: 'Setup Node.js and pnpm, install, and cache pnpm store'
runs:
  using: "composite"
  steps:
    - name: Install Node.js
      uses: actions/setup-node@v6.2.0
      with:
        node-version: 24

    # https://github.com/pnpm/action-setup/issues/201
    - uses: pnpm/action-setup@9b5745cdf0a2e8c2620f0746130f809adb911c19
      name: Install pnpm
      with:
        cache: true

    - name: Install dependencies
      shell: bash
      run: pnpm install