name: 'Prepare job'
description: 'Setup Node.js and pnpm, install, and cache pnpm store'
runs:
  using: "composite"
  steps:
    - name: Install Node.js
      uses: actions/setup-node@v6.2.0
      with:
        node-version: 24

    # https://github.com/pnpm/action-setup/issues/201
    - uses: pnpm/action-setup@1e1c8eafbd745f64b1ef30a7d7ed7965034c486c
      name: Install pnpm
      with:
        cache: true

    - name: Install dependencies
      shell: bash
      run: pnpm install