name: PR Title Check

permissions:
  contents: read

on:
  pull_request:
    types: [opened, reopened, synchronize, edited]

concurrency:
  group: check-pr-title-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check_pr_title:
    name: Title has jira ticket id
    runs-on: 'ubuntu-latest'
    if: ${{ github.actor != 'renovate[bot]' || github.actor != 'mergify[bot]' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get jira ids
        shell: bash
        run: |
          GREEN="\033[0;32m"
          YELLOW="\033[1;33m"
          CYAN="\033[0;36m"
          RED="\033[0;31m"
          NC="\033[0m"

          STRING=$(echo "${{ github.event.pull_request.title }}")

          echo -e "${CYAN}Checking string...${NC}"
          echo -e "${YELLOW}$STRING${NC}"
          echo

          # Remove new lines and leading/trailing spaces
          CLEAN_STRING=$(echo "$STRING" | head -n1 | sed -E 's/^ *//; s/ *$//')

          echo -e "${GREEN}Cleaned string!${NC}"
          echo -e "${YELLOW}$CLEAN_STRING${NC}"
          echo

          # Extract Jira IDs enclosed in square brackets
          MATCHED_IDS=$(echo "$CLEAN_STRING" | grep -Eo '^\[[^]]*[a-zA-Z]+-[0-9]+[^]]*\]')

          # Remove square brackets from the matched IDs
          CLEANED_IDS=$(echo "$MATCHED_IDS" | sed -E 's/^\[|\]$//g')

          # Split IDs by commas/spaces and extract Jira IDs
          VALID_IDS=$(echo "$CLEANED_IDS" | tr ', ' '\n' | grep -E '^[a-zA-Z]+-[0-9]+$')

          # Combine Jira IDs into a comma-separated string
          JIRA_IDS=$(echo "$VALID_IDS" | paste -sd, - || true)

          echo -e "JIRA_IDS=${GREEN}$JIRA_IDS${NC}"
          echo

          if [ -z "${JIRA_IDS}" ]; then
            echo -e "${RED}Jira id(s) missing from PR title.${NC}"
            echo

            exit 1
          fi

          echo "jira_ids=$JIRA_IDS" >> "$GITHUB_OUTPUT"
          cat "$GITHUB_OUTPUT"
