name: Dispatch Jira Action

on:
  workflow_dispatch:
  push:
    branches:
      - ink-91

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare job
        uses: ./.github/actions/prepare-job

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22.12.0'

      - name: "Debug: curl Jira search"
        env:
          JIRA_CLASSIC_API_TOKEN: ${{ secrets.JIRA_CLASSIC_API_TOKEN }}
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_EMAIL: ${{ secrets.JIRA_EMAIL }}
          JQL: 'project = inkbeard AND status = "To Do"'
        run: |
          echo 'Running debug curl against Jira search/jql'
          ENCODED=$(node -e "console.log(encodeURIComponent(process.env.JQL))")
          curl -sS -u "$JIRA_EMAIL:$JIRA_CLASSIC_API_TOKEN" -H "Accept: application/json" "${JIRA_BASE_URL}/rest/api/3/search/jql?jql=${ENCODED}" | jq '.' || true

      - name: Build package
        run: pnpm --filter jira-workflow build

      - name: Run local action
        uses: ./packages/jira-workflow
        with:
          jql: 'project = inkbeard AND status = "To Do"'
        env:
          JIRA_API_TOKEN: ${{ secrets.JIRA_CLASSIC_API_TOKEN }}
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_EMAIL: ${{ secrets.JIRA_EMAIL }}
