name: Install & test

on:
  pull_request:
    types: [opened, synchronize, reopened]

concurrency: ${{ github.workflow }}-${{ github.ref }}

env:
  IS_CHANGELOG_PR: ${{ github.event.pull_request.title == vars.CHANGELOG_PR_TITLE }}

jobs:
  install_dependencies:
    name: Install dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        if: env.IS_CHANGELOG_PR != 'true'
        uses: actions/checkout@v6.0.2

      - name: Prepare job
        if: env.IS_CHANGELOG_PR != 'true'
        uses: ./.github/actions/prepare-job

  run_unit_tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    needs: install_dependencies
    steps:
      - name: Checkout
        if: env.IS_CHANGELOG_PR != 'true'
        uses: actions/checkout@v6.0.2

      - name: Prepare job
        if: env.IS_CHANGELOG_PR != 'true'
        uses: ./.github/actions/prepare-job

      - if: env.IS_CHANGELOG_PR != 'true'
        run: pnpm test:unit

  run_lint:
    name: Run lint
    runs-on: ubuntu-latest
    needs: install_dependencies
    steps:
      - name: Checkout
        if: env.IS_CHANGELOG_PR != 'true'
        uses: actions/checkout@v6.0.2

      - name: Prepare job
        if: env.IS_CHANGELOG_PR != 'true'
        uses: ./.github/actions/prepare-job

      - if: env.IS_CHANGELOG_PR != 'true'
        run: pnpm lint

  run_stylelint:
    name: Run stylelint
    runs-on: ubuntu-latest
    needs: install_dependencies
    steps:
      - name: Checkout
        if: env.IS_CHANGELOG_PR != 'true'
        uses: actions/checkout@v6.0.2

      - name: Prepare job
        if: env.IS_CHANGELOG_PR != 'true'
        uses: ./.github/actions/prepare-job

      - if: env.IS_CHANGELOG_PR != 'true'
        run: pnpm stylelint

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: install_dependencies
    steps:
      - name: Checkout
        if: env.IS_CHANGELOG_PR != 'true'
        uses: actions/checkout@v6.0.2

      - name: Prepare job
        if: env.IS_CHANGELOG_PR != 'true'
        uses: ./.github/actions/prepare-job

      - if: env.IS_CHANGELOG_PR != 'true'
        run: pnpm build