name: Install & test

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  install_dependencies:
    name: Install dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare job
        uses: ./.github/actions/prepare-job

  run_unit_tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    needs: install_dependencies
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare job
        uses: ./.github/actions/prepare-job

      - run: pnpm test:unit

  run_lint:
    name: Run lint
    runs-on: ubuntu-latest
    needs: install_dependencies
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare job
        uses: ./.github/actions/prepare-job

      - run: pnpm lint

  run_stylelint:
    name: Run stylelint
    runs-on: ubuntu-latest
    needs: install_dependencies
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare job
        uses: ./.github/actions/prepare-job

      - run: pnpm stylelint

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: install_dependencies
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare job
        uses: ./.github/actions/prepare-job

      - run: pnpm build