name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2

      - name: Prepare job
        uses: ./.github/actions/prepare-job

      - name: Generate token
        id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.INKBEARD_APP_ID }}
          private-key: ${{ secrets.INKBEARD_AUTOMATION_KEY }}

      - name: Create Release Pull Request
        uses: changesets/action@v1.7.0
        with:
          commit: ${{ vars.CHANGELOG_PR_TITLE }}
          commitMode: github-api
          title: ${{ vars.CHANGELOG_PR_TITLE }}
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}