name: Add changeset to renovate PRs

on:
  pull_request:
    types: [opened, synchronize, labeled]

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  renovate:
    name: Update Renovate PR
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'dependencies')

    steps:
      - name: Update PR
        uses: mscharley/dependency-changesets-action@v1.1.1
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}
          use-conventional-commits: true
